name: test-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - pip
  - git
  - cmake
  - pip:
    - --use-feature=no-binary-enable-wheel-cache h5py
    - meshio
    - git+https://github.com/SVMTK/SVMTK.git
  